Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: 节点测速
+name: free-v2ray-node
 
 on:
   schedule:
@@ -33,9 +33,14 @@ jobs:
 
       - name: Commit and push file
         run: |
+          set +e
           git config user.name "github-actions[bot]"
           git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git add v2ray.txt all.txt v2ray_raw.txt
           git commit -m "update" || echo "No changes to commit"
           git pull --rebase
-          git push https://${{ secrets.BOT }}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git
+          if [ $? -ne 0 ]; then
+            git rebase --abort
+            echo "rebase failed, will force push"
+          fi
+          git push --force https://${{ secrets.BOT }}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git
